version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: hr_postgres
    restart: always
    environment:
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_password
      POSTGRES_DB: hr_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8081:8080"

  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8020:8020"
    volumes:
      - ./data/job_description:/app/data/job_description
      - ./data/resume:/app/data/resume
      - ./data/job_description_extractor:/app/data/job_description_extractor
      - ./data/resume_extractor:/app/data/resume_extractor
      - .:/app
    depends_on:
      - postgres

volumes:
  postgres_data:
